# <div style="color:red;text-align:center;">9、访问数组元素</div>

numpy中，可以像普通数组一样用下标来访问元素，比如a[1][1]、a[1,1]

---

**numpy中通过索引访问数组元素**

a[1,:]（访问第1行元素）

a[:,1]（访问第1列元素）

a[1,1:3]（访问第1行的，第1-2列元素）

### 1、pyhton列表中访问元素

In [12]:
list1=[[1,2,3,4],[5,6,7,8]]
print(list1)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [13]:
print(list1[1])

[5, 6, 7, 8]


In [14]:
print(list1[1][1])

6


In [18]:
print(list1[1:2])

[[5, 6, 7, 8]]


In [15]:
# 不支持
print(list1[1,1])

TypeError: list indices must be integers or slices, not tuple

In [17]:
# 不支持
print(list1[1:2,1:2])

TypeError: list indices must be integers or slices, not tuple

### 2、numpy数组访问元素

In [1]:
import numpy as np
arr=np.arange(4,20).reshape(4,4)
print(arr)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [2]:
print(arr[1])

[ 8  9 10 11]


In [4]:
print(arr[1][2])
print(arr[1,2])

10
10


In [5]:
# 逗号前面的表示行
# 逗号后面的表示列
# 留头不留尾
print(arr[1:3,1:3])

[[ 9 10]
 [13 14]]


In [6]:
print(arr[2:4,1:4])

[[13 14 15]
 [17 18 19]]


In [8]:
print(arr)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [9]:
print(arr[:,1:4])

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [10]:
print(arr[1:4,:])

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [11]:
print(arr[1,:])

[ 8  9 10 11]
