# <div style="color:red;text-align:center;">11、数组合并</div>

### 1、水平合并：

horizontal stack

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [2]:
# 合并数组
# 左右合并 horizontal stack
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


### 2、垂直合并：

vertical stack

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# 合并数组
# 垂直合并 vertical stack
c = np.vstack((a,b))
print(c)
print(a.shape)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)


### 3、concatenate方法

In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


**垂直合并**

In [5]:
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]]


In [6]:
# axis=0 纵轴
print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]
 [5 6]]


**水平合并**

In [7]:
print(a)
print(b.T)

[[1 2]
 [3 4]]
[[5]
 [6]]


In [8]:
print(np.hstack((a, b.T)))

[[1 2 5]
 [3 4 6]]


In [9]:
# axis=1 横轴
print(np.concatenate((a, b.T), axis=1))


[[1 2 5]
 [3 4 6]]
