# <div style="color:red;text-align:center;">10、遍历数组元素</div>

**numpy中如何迭代列**

将矩阵转置即可

~~~
# 迭代列 (转置一下即可实现)
for i in a.T:
    print(i)
~~~

---

**numpy中如何迭代多维数组的每一个数**

    for i in a.flat: 
        print(i)

In [6]:
import numpy as np
arr=np.arange(4,20).reshape(4,4)
print(arr)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### 1、迭代行

In [7]:
for i in arr:
    print(i)

[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


### 2、迭代列

转置一下即可很方便的迭代列

In [8]:
for i in arr.T:
    print(i)

[ 4  8 12 16]
[ 5  9 13 17]
[ 6 10 14 18]
[ 7 11 15 19]


### 3、迭代每个元素

In [9]:
# 打平数组
print(arr.flatten())

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
for i in arr.flatten():
    print(i)

4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [11]:
for i in arr.flat:
    print(i)

4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
# flatten() 和 flat的区别
# flat是一个迭代器

In [12]:
for i in arr:
    for j in i:
        print(j)

4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
